[build]
builder = "nixpacks"

[deploy]
startCommand = "node index.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "reverse-bot"
